- name: Check if homebrew is available
  vars:
    install_homebrew_if_missing: false
    upgrade_homebrew_packages: false
  tags:
    - neovim
    - tmux
  block:
    - name: Ensuring Homebrew Is Installed
      tags:
        - neovim
        - tmux
      stat:
        path: /opt/homebrew/bin/brew
      register: homebrew_check

    - name: Fail If Homebrew Is Not Installed and install_homebrew_if_missing Is False
      tags:
        - neovim
        - tmux
      fail:
        msg: Homebrew is missing...Install from http://brew.sh/
      when:
        - not homebrew_check.stat.exists
        - not install_homebrew_if_missing

    - name: Installing Homebrew
      tags:
        - neovim
        - tmux
      shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      when:
        - not homebrew_check.stat.exists
        - install_homebrew_if_missing

    - name: Updating Homebrew
      tags:
        - neovim
        - tmux
      homebrew:
        update_homebrew: true
      when: homebrew_check.stat.exists

    - name: Installing tmux
      homebrew:
        name: tmux
        state: present
      tags:
        - tmux
      register: result
      until: result is successful
      when: homebrew_check.stat.exists

    - name: Installing neovim
      homebrew:
        name: neovim
        state: present
      tags:
        - neovim
      register: result
      until: result is successful
      when: homebrew_check.stat.exists

  rescue:
    - name: No homebrew
      debug:
        msg: Homebrew is not installed

